name: helloworld
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0
  flutter_contacts: ^1.1.8
  cupertino_icons: ^1.0.2
  battery_plus: ^6.0.0
  razorpay_flutter: ^1.3.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  google_sign_in: ^6.1.5
  share_plus: ^9.0.0
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  image_picker: ^1.0.5
  geolocator: ^10.1.0
  url_launcher: ^6.2.2
  intl: ^0.19.0
  speech_to_text: ^6.5.1
  google_mlkit_language_id: ^0.9.0
  tflite_flutter: ^0.10.4
  sound_stream: ^0.4.0
  ffi: ^2.1.0
  path_provider: ^2.1.2
  mailer: ^6.1.0
  google_fonts: ^6.1.0
  permission_handler: ^11.3.0
  integration_test:
    sdk: flutter
  firebase_database: ^10.5.7
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1
  http: ^1.2.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
